### ISSUE TITLE
missing DateWrapper use in @seriesobj and @tableobj

### ISSUE THREAD

**Issue by nul0m** [IRIS-Solutions-Team/IRIS-Toolbox#83] opened 2017-10-09 17:35 UTC
please see this failing test:
https://teamcity.igpmn.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=308&_focus=1542

I'd suggest the following patch, but not sure if this is all we need to fix:

```
diff --git a/+report/@seriesobj/getdata.m b/+report/@seriesobj/getdata.m
index 25ec0d3..c64fe6c 100644
--- a/+report/@seriesobj/getdata.m
+++ b/+report/@seriesobj/getdata.m
@@ -29,6 +29,9 @@ end
         % frequency.
         if isequal(Range,Inf) || length(Inp) == 1
             [Outp,Time] = Inp{1}(Range,:);
+            if isa(Range,'DateWrapper')
+              Time = DateWrapper(Time);
+            end
             return
         end
         Time = Range;
diff --git a/+report/@tableobj/tableobj.m b/+report/@tableobj/tableobj.m
index a4384a0..8d25046 100644
--- a/+report/@tableobj/tableobj.m
+++ b/+report/@tableobj/tableobj.m
@@ -59,7 +59,11 @@ classdef tableobj < report.tabularobj
             This.options.vlineafter = ...
                 [This.options.vlineafter(:).', ...
                 rng(inxAfter)];
-            This.options.range = rng;
+            if isa(This.options.range,'DateWrapper')
+              This.options.range = DateWrapper(rng);
+            else
+              This.options.range = rng;
+            end
             
             isDates = isempty(This.options.colstruct);
             if ~isDates
```

**Comment by jaromir-benes** [comment] 2017-10-09 19:37
Thanks for catching this one, Sergey. The problem is somewhere else (in the
parent table object). I'll fix it tomorrow, hopefully.

**Comment by nul0m** [comment] 2017-10-10 06:39
sure, this patch was some kind of supportive therapy )
actually, `@tseries/subsref.m` may also return DateWrapper for the second output arg, what do you think?

**Comment by jaromir-benes** [comment] 2017-10-10 06:44
sorry, i must've had not enough coffee yet ... what exactly did you mean by
the @tseries/subsref thing?

**Comment by nul0m** [comment] 2017-10-10 06:48
in `report/@seriesobj/getdata.m` you use this expression:
```
[Outp,Time] = Inp{1}(Range,:);
```
the Time is not a DateWrapper
so I thought that `subsref` method of `@tseries` class may be adjusted to return a DateWrapper object for the second output argument (`Time` in this case)

**Comment by jaromir-benes** [comment] 2017-10-10 06:51
Ok, it definitely should be a DateWrapper. I'll look into it. Thanks.

**Comment by jaromir-benes** [comment] 2017-10-10 14:34
Fixed in repo.

**Closed as completed by jaromir-benes** 2017-10-10 14:34 UTC
